name: weathercock

services:
  postgres:
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    container_name: weathercock-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - weathercock-net
    secrets:
      - postgres_admin
      - postgres_app_user
    volumes:
      - ./configs/postgres/config.d:/etc/postgresql/config.d
      - ./configs/postgres/init.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD_FILE: /run/secrets/postgres_app_user
      POSTGRES_APP_DB: ${POSTGRES_APP_DB}
    command: [ "-c", "config_file=/etc/postgresql/config.d/postgres.conf" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
  valkey:
    image: ${VALKEY_IMAGE}:${VALKEY_TAG}
    container_name: weathercock-valkey
    restart: always
    ports:
      - "${VALKEY_PORT}:6379"
    networks:
      - weathercock-net
    secrets:
      - valkey_acl
    volumes:
      - ./configs/valkey:/usr/local/etc/valkey
      - valkey_data:/data/valkey/snapshots
    command: [ "valkey-server", "/usr/local/etc/valkey/valkey.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  nats:
    image: ${NATS_IMAGE}:${NATS_TAG}
    container_name: weathercock-nats
    restart: always
    ports:
      - "${NATS_CLI_PORT}:4222"
      - "${NATS_HTTP_PORT}:8222"
    networks:
      - weathercock-net
    volumes:
      - ./configs/nats:/etc/nats
      - nats_data:/data/nats
    command: [ "-js", "-sd", "/data/nats/jetsteam", "-c", "/etc/nats/nats-server.conf", --user, "${NATS_USER}", --pass, "${NATS_PASS}" ]
  jaeger:
    image: ${JAEGER_IMAGE}:${JAEGER_TAG}
    container_name: weathercock-jaeger
    restart: always
    ports:
      - "${JAEGER_OTEL_PORT}:4317"
      - "${JAEGER_HTTP_PORT}:4318"
      - "${JAEGER_PORT}:5775"
      - "${JAEGER_GRPC_PORT}:14250"
      - "${JAEGER_HTTP_UI_PORT}:16686"
    networks:
      - weathercock-net
    volumes:
      - jaeger_data:/data/jaeger

volumes:
  postgres_data:
  nats_data:
  valkey_data:
  jaeger_data:


networks:
  weathercock-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

secrets:
  postgres_admin:
    file: .secrets/postgres_admin
  postgres_app_user:
    file: .secrets/postgres_app
  valkey_acl:
    file: ${VALKEY_ACL_FILE}
