FROM golang:1.24

ARG USERNAME
ARG USER_UID
ARG USER_GID=${USER_UID}

RUN groupadd -g ${USER_GID} ${USERNAME} && \
    useradd -m -u ${USER_UID} -g ${USER_GID} ${USERNAME} && \
    apt-get update && apt-get install -y git curl sudo && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /home/${USERNAME}/app
RUN chown -R ${USER_UID}:${USER_GID} /home/${USERNAME}/
RUN go install github.com/go-task/task/v3/cmd/task@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

ENV GOPATH=/home/${USERNAME}/go
ENV PATH="${GOPATH}/bin:${PATH}"

USER ${USERNAME}

CMD ["sleep", "infinity"]