name: weathercock-dev

services:
  nui:
    image: ${NUI_IMAGE}:${NUI_TAG}
    container_name: weathercock-dev-nui
    restart: always
    depends_on:
      - nats
    ports:
      - "${NUI_PORT}:31311"
    volumes:
      - nui_data:/db
  pgadmin:
    image: ${PGADMIN_IMAGE}:${PGADMIN_TAG}
    container_name: weathercock-dev-pgadmin
    restart: always
    depends_on:
      - postgres
    secrets:
      - pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin
  test:
      build:
        context: .
        dockerfile: Dockerfile.dev
        args:
          USERNAME: ${DEV_USERNAME}
          USER_UID: ${DEV_UID}
          USER_GID: ${DEV_GID}
      container_name: weathercock-dev-test
      working_dir: /home/${DEV_USERNAME}/app
      volumes:
        - .:/home/${DEV_USERNAME}/app
      tty: true
      stdin_open: true
      command: sleep infinity
      environment:
        DISPLAY: ${DEV_DISPLAY}
        WAYLAND_DISPLAY: ${DEV_WAYLAND_DISPLAY}
      depends_on:
        - postgres
        - valkey
        - nats
      secrets:
        - postgres_admin
        - postgres_app_user

volumes:
  nui_data:
  pgadmin_data:

secrets:
  pgadmin:
    file: .secrets/pgadmin4
