# https://taskfile.dev

version: "3"

env:
  CSS_SRC: "src/css/style.css"
  CSS_DST: "static/css/style.css"
  PROTOBUF_SRC: "proto"
  PROTOBUF_DST: "."

dotenv: [".env"]

tasks:
  docker-compose-up:
    desc: Start the Docker containers for development (including NUI and pgAdmin)
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d
  docker-compose-down:
    desc: Stop the Docker containers for development 
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose-dev.yml down
  go-run-api:
    desc: Run the API server
    cmds:
      - go run ./cmd/api/main.go
  go-run-worker:
    desc: Run the worker server
    cmds:
      - go run ./cmd/worker/main.go
  go-run-scraper:
    desc: Run the scraper
    cmds:
      - go run ./cmd/scraper/main.go
  migrate-up:
    desc: Run database migrations
    cmds:
      - bash ./scripts/migrate.sh up
  migrate-down:
    desc: Rollback database migrations  
    cmds:
      - bash ./scripts/migrate.sh down
  migrate-force:
    desc: Force database migrations to given version
    requires:
      vars:
        - version
    cmds:
      - bash ./scripts/migrate.sh force {{.version}}
  watch-css:
    desc: Watch for changes in style.css and compile them
    cmds:
      - npx @tailwindcss/cli -i "$CSS_SRC" -o "$CSS_DST" --watch
  clean-css:
    desc: Clean the CSS file
    cmds:
      - rm -f "$CSS_DST"
  build-css:
    desc: Build the CSS file
    cmds:
      - npx @tailwindcss/cli -i "$CSS_SRC" -o "$CSS_DST" --minify
  build-protobuf:
    desc: Generate Go code from protobuf definitions
    cmds:
      - protoc -I="$PROTOBUF_SRC" --go_out="$PROTOBUF_DST" $PROTOBUF_SRC/*.proto 