// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO users.tasks (
    source,
    original_input
) VALUES (
    $1,
    $2
)
RETURNING task_id
`

type CreateTaskParams struct {
	Source        SourceType `db:"source" json:"source"`
	OriginalInput string     `db:"original_input" json:"original_input"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Source, arg.OriginalInput)
	var task_id uuid.UUID
	err := row.Scan(&task_id)
	return task_id, err
}
