ALTER SEQUENCE users.tasks_id_seq RESTART WITH 1;

DROP TABLE IF EXISTS users.tasks;

DROP TYPE IF EXISTS source_type;

DROP TABLE IF EXISTS users.info;

DROP SCHEMA IF EXISTS users;

DROP TYPE IF EXISTS task_status;